### ISSUE TITLE
[Bug] Couldn't render a page - Couldn't paint Context: Invalid Matrix

### ISSUE THREAD

**Issue by mcxiv** [itsjunetime/tdf#1]
Hello there,

tdf looks fantastic! Good job!

I saw that someone reported the same issue as me on Reddit and hasn't created the issue yet, so, here I am.

------------------------------------------------

I am using Terminator, and, for any PDF file I'm trying, I am getting the error 
"Couldn't render a page: Couldn't render page: Couldn't paint Context: Invalid Matrix"

![image](https://github.com/itsjunetime/tdf/assets/43221669/aea4e0b9-05d4-4bb0-a623-76f18e126464)

You mentioned the fact that it could be because of terminator, but I am getting the same error on the Manjaro (gnome) default terminal. (Works well on kitty tho)

Thanks,
Quentin

**Comment by dashingdon** [comment]
it was me who reported @mcxiv . thank you for opening the issue.  

I blurred the file name at the top. rest is direct output of tdf

- For me it's not even working for `kitty`. Screenshot below
  ![image](https://github.com/itsjunetime/tdf/assets/15974333/c54d6608-ae5c-4712-be73-c6ac86e8deaa)

- `xterm` - loads it quickly but the content is all fuzzy
  
  ![image](https://github.com/itsjunetime/tdf/assets/15974333/ea361977-d736-480e-a308-8fc04ecd963b)

**Comment by gmkanat** [comment]
same issue, does not work on ubuntu, ping me when you find solution

**Comment by dashingdon** [comment]
@itsjunetime @mcxiv will you be able to share your kitty configuration? I am trying to get it working on kitty (I am using default kitty config). Attached are my current laptop specs (if helpful)

![image](https://github.com/itsjunetime/tdf/assets/15974333/14add87e-c3d1-4068-8af5-c60855216f1c)

**Comment by itsjunetime** [comment]
Before I share my config (as I don't think kitty has any options in the config that change image support), @dashingdon would you be able to paste the output of running `kitty +kitten icat --detect-support; echo "$?"` in a running instance of kitty?

**Comment by dashingdon** [comment]
> kitty +kitten icat --detect-support; echo "$?"

file0

**Comment by crookedmirror** [comment]
Getting same issue on Sakura terminal here. Is only kitty supported?

**Comment by dashingdon** [comment]
@itsjunetime  quick update re `Kitty` I updated the version to latest (0.35 [link](https://sw.kovidgoyal.net/kitty/binary/#nightly)). debian repo version was 0.26.5

kitty works great. thank you.

**Comment by joseg-alvesg** [comment]
> * `xterm` - loads it quickly but the content is all fuzzy
>   ![image](https://private-user-images.githubusercontent.com/15974333/335032154-ea361977-d736-480e-a308-8fc04ecd963b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjI0OTcsIm5iZiI6MTcxNzEyMjE5NywicGF0aCI6Ii8xNTk3NDMzMy8zMzUwMzIxNTQtZWEzNjE5NzctZDczNi00ODBlLWEzMDgtOGZjMDRlY2Q5NjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAyMjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YTNkMzcyNzAyYjVkMTUyOTM3MWIwMWRkMGVkNzRiY2RhNGE2NzZmZWU0MTMwZTRhNDc3MzAyMjMxMTU2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RIoAmmfc5cY7t3astur0iYdeElJFpQOgZbGjcU8TDMQ)

The same happens in alacritty

![image](https://github.com/itsjunetime/tdf/assets/83045613/e4f27d46-2108-46d4-bcfb-001dd1c7d6cc)

**Comment by itsjunetime** [comment]
With regard to alacritty, please read this comment: https://github.com/itsjunetime/tdf/issues/3#issuecomment-2138000680; however, it seems xterm might be having a different issue, as it should support sixel (as per https://www.arewesixelyet.com/#xterm). @dashingdon would you be able to open another issue for the xterm fuzziness (as it should work fine there)? 

I'd like to keep this issue on the topic of, specifically, the 'Invalid Matrix' error. If anyone has suggestions for what to do about that error (after reading my comments in https://github.com/itsjunetime/tdf/issues/1#issuecomment-2138019290), I would appreciate that being discussed here.

**Comment by dashingdon** [comment]
>  @dashingdon would you be able to open another issue for the xterm fuzziness (as it should work fine there)?

Done :heavy_check_mark:

**Comment by itsjunetime** [comment]
I just pushed https://github.com/itsjunetime/tdf/commit/017596a8b0745a6da7c3c75a5f55073b82202a5c, which fixes this issue for me on terminator (of course, it still shows up as blurry halfblocks due to the lack of image support, but at least it doesn't report the invalid matrix); @mcxiv could you confirm that this issue is now not present?

**Comment by dashingdon** [comment]
> I just pushed https://github.com/itsjunetime/tdf/commit/017596a8b0745a6da7c3c75a5f55073b82202a5c, which fixes this issue for me on terminator

I confirm that file renders (fuzzy as expected) but no `invalid matrix` error

![image](https://github.com/itsjunetime/tdf/assets/15974333/a09b562e-e15e-487d-a2a1-e03789ab505e)

**Comment by dashingdon** [comment]
also [fyi](https://github.com/gnome-terminator/terminator/pull/770) looks like sixel support has been enabled for terminator. now sure how to activate/enable it

**Comment by itsjunetime** [comment]
According to https://github.com/fastfetch-cli/fastfetch/issues/683#issuecomment-1890576703, terminator does have sixel support iff the underlying vte (i think that stands for virtual terminal emulator? maybe?) was compiled with sixel support. I'm guessing, then, that the default underlying vte does not have sixel support and you'd need to do a custom build to get that.

Also, since the titular issue here has been resolved, I'm going to close this issue.

**Comment by j4james** [comment]
@beammeout Sixel was never part of the vte stable branch. I think what you're seeing in that commit is just how they merge the master branch into the stable branch while filtering out the parts that aren't actually stable yet. So if you want the sixel functionality, you'll need to build vte from the master branch.

That said, the sixel support in the master branch doesn't really work anymore - you'll just see gaps in the display where the images are meant to be. It broke when they implemented GTK4 drawing in commit [c557b230](https://gitlab.gnome.org/GNOME/vte/-/commit/c557b2300c835f0d22b6647c9155efdf101d0c2e). So if you want it to actually work, you'll probably need to build from a commit prior to that.

**Comment by beammeout** [comment]
@j4james Thanks, I ended up doing something of the sorts and could get it working!
