### ISSUE TITLE
can not build on alpine/pmos

### ISSUE THREAD

**Issue by magdesign** [itsjunetime/tdf#11]
it complains about base64

``` Compiling vb64 v0.1.2 (https://github.com/lukaslihotzki/vb64?branch=update#01e79118)
   Compiling icy_sixel v0.1.2
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/me/.cargo/git/checkouts/vb64-dd52a41bf8543107/01e7911/src/lib.rs:36:12
   |
36 | #![feature(portable_simd)]
   |            ^^^^^^^^^^^^^

   Compiling base64 v0.22.1
For more information about this error, try `rustc --explain E0554`.
error: could not compile `vb64` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish... ```

**Comment by itsjunetime** [comment]
This tool needs to be built with the nightly toolchain. Normally, the `rust-toolchain.toml` file is read by `cargo` to determine the toolchain to use to compile, but this error implies that's not exactly going on here. Could you update to the very latest nightly toolchain with `rustup update nightly` and try again? And if it still fails, could you put minimal reproduction steps here?

**Comment by magdesign** [comment]
thanks for your response. i will try (my system broke caused by something, so need to fix this first)

**Comment by itsjunetime** [comment]
Closing; seems pretty clear it's a local issue.

**Comment by magdesign** [comment]
` cargo build --release --no-default-features`

fixes the problem and builds tdf
