### ISSUE TITLE
Feature Request: Right-to-Left Binding

### ISSUE THREAD

**Issue by tower2149** [itsjunetime/tdf#12]
I am writing to request a new feature for your PDF viewer: support for right-to-left binding.

Many languages, including Arabic, Hebrew, and Japanese vertical text, are traditionally read from right to left. When viewing PDFs of these documents, it is much more natural and convenient to have the binding on the right side.

**Comment by itsjunetime** [comment]
Yes, I'd be happy to add this! I'm not certain I'm following what you mean with having the binding on the right side, though - pages are currently centered, so I'm not sure what UI/input elements would need to be switched around. Could you expand on that a bit?

**Comment by alerque** [comment]
I think they mean page order should be switched so the lower page number is on the right. Right now pages go:

```
1 | 2
3 | 4
```

An primarily RTL document should be rendered:

```
2 | 1
4 | 3
```

**Comment by tower2149** [comment]
Yes.
I refered about "bound on the right-hand side"
![image](https://github.com/user-attachments/assets/0aa30216-3528-4939-b92a-b7db046ccffe)

**Comment by itsjunetime** [comment]
Alright, it took me a second but I got around to this and just pushed a commit that added a cli feature flag that should do what you were hoping for (e51e9d34645aaed6b9caee17ea95f69f4a5a4067) - I'm going to close this issue for now, then, but let me know if this flag doesn't do exactly what you were looking for or needs to do more to accommodate this feature.
