### ISSUE TITLE
shows only block characters

### ISSUE THREAD

**Issue by alexanderkjeldaas** [itsjunetime/tdf#21]
Maybe the README could indicate what to fix when only block characters are visible?

![image](https://github.com/user-attachments/assets/f57181ca-a15f-4a1a-9170-c38d4c3568a2)

**Comment by ijakenorton** [comment]
ah, yeah I have the same issue
![image](https://github.com/user-attachments/assets/55f4c8f4-8bc4-4c4e-abab-39387f9eeb4e)

**Comment by ijakenorton** [comment]
Ah realized this is a copy of #3 could be good for the readme so this doesn't keep happening I guess

**Comment by itsjunetime** [comment]
Yes, this is a copy of 3, but it has come up a good amount, so I think I'll just pin it to the top so it can be easily found.
