### ISSUE TITLE
Option to reload.

### ISSUE THREAD

**Issue by leissa** [itsjunetime/tdf#24]
Steps to reproduce:

* `pdflatex test.tex`
* `tdf test.pdf`
* `rm test.pdf`
* -> tdf display Error: `Couldn't render a page: Couldn't open document: No such file or directory`
* `pdflatex test.tex`
* -> tdf still displays error

Would be cool, if tdf would be able to detect that the file is there again and maybe add a key `r` to reload, if everything else fails.

**Comment by itsjunetime** [comment]
Are you running latest main? This used to be an issue, but afaik it was fixed when I pushed 4296c92d7d91b210149ecfb8dd72e487fb747eff - if you haven't been running latest main, would you be able to update and try again?

**Comment by jpyamamoto** [comment]
I can confirm that the error message stays visible even after the file is regenerated. I'm running latest main.

**Comment by itsjunetime** [comment]
Ok, I actually took the time to figure this out today and it *actually* should be good now, as of https://github.com/itsjunetime/tdf/commit/0129c498c2fe5770ed436df86937260d12024c89. I'd like to release version 0.2.0 soon, so if one of you two would be able to make sure things look good now, that would be great.

**Comment by jpyamamoto** [comment]
I can confirm it's working as expected now. Thank you @itsjunetime
