### ISSUE TITLE
pages not properly rendered

### ISSUE THREAD

**Issue by wanghuibin0** [itsjunetime/tdf#29]
I use the command: tdf file.pdf, and the pdf is opened but not properly rendered.
The words cannot be seen clearly, like the following:
![image](https://github.com/user-attachments/assets/a78b00b0-8711-429b-a43e-7b5456bfc1c8)

Is there something wrong that I did?

**Comment by itsjunetime** [comment]
Please check other issues before filing new ones. This is already the pinned issue: #3.

**Comment by wanghuibin0** [comment]
@itsjunetime OK, thank you very much
