### ISSUE TITLE
tdf hangs on windows

### ISSUE THREAD

**Issue by Kreijstal** [itsjunetime/tdf#35]
So I made some unholy code here https://github.com/Kreijstal/tdf/tree/windows where I managed to make tdf compile.  https://news.ycombinator.com/item?id=40847204
It hangs and never shows any pdf.

I know windows isn't supported, I just wanted to announce that I tried and failed, maybe it will help someone (unlikely).

**Comment by itsjunetime** [comment]
I appreciate you trying, maybe somebody will be able figure this out at some later point. Since there's not much to do with this at the moment, though, I'm going to close this issue for now.
