### ISSUE TITLE
AUR PAckage not building

### ISSUE THREAD

**Issue by xircon** [itsjunetime/tdf#39]
Apologies, will update post with errors when I got home (had to dash out), spews a load of errors and fails to compile.

**Comment by alerque** [comment]
The PKGBUILD needs to disable LTO, this is a problem with the AUR package not with this project. I'll comment on the fix in the AUR comments, but this issue can be closed.

**Comment by itsjunetime** [comment]
Yes, the AUR package is not under my control so I can't do anything about this.
