### ISSUE TITLE
Can't go back

### ISSUE THREAD

**Issue by DieracDelta** [itsjunetime/tdf#5]
`j` works to go to the next page. `k` decrements the counter but the displayed content does not change. I'm on nixos and compiled with 1.80.0-nightly f3df08aa on ghostty. I'm betting some behavior changed based on terminal and toolchain. Which terminal and toolchain has this been tested on?

**Comment by itsjunetime** [comment]
I've been testing this with nightly toolchains for the past month or so - currently, I'm running `rustc 1.80.0-nightly (6f3df08aa 2024-05-30)` and those keys work fine on kitty, xterm, and terminator. I'm not certain how to get access to ghostty to test this (I saw something about it being available on the zig package manager, but I'm not quite certain how to use that), so I don't know how to test/debug this.

Are you seeing this same issue on terminals besides ghostty, e.g. kitty or wezterm?

**Comment by itsjunetime** [comment]
Sorry, I've been waiting for a bit to try this out, but ghostty is built with zig, and that language still doesn't work on aarch64 linux (which is what I use) - I was hoping to help out here, but it's clearly an issue with ghostty instead of tdf, so I'm going to close this.
