### ISSUE TITLE
Render very pixelated on alacritty

### ISSUE THREAD

**Issue by Mithrandir2k18** [itsjunetime/tdf#6]
I usually use alacritty with TMUX. TERM is set to 'screen-256color', on alacritty without tmux it's set to 'alacritty'. Setting it to e.g. 'linux' or 'xterm' also has the same pixelated result.

On kitty however, pdfs render perfectly.

Any tips what I could look into to fix it?

**Comment by itsjunetime** [comment]
Please read previous issues before filing a new one :) This comment should explain what's happening here: https://github.com/itsjunetime/tdf/issues/3#issuecomment-2138000680

**Comment by Mithrandir2k18** [comment]
Sorry, for whatever reason I skipped looking at old issues, shame on me. Thanks anyways, looks like this isn't going to work with tmux in any combination.
